### ISSUE TITLE
Smallish things in objects

### ISSUE THREAD

**Issue by BakermanLP** [BiomeBundle/BiomeBundle#10]
Hello, it's me again :)

There are some minor things I found by updating my repository.

https://github.com/BiomeBundle/BiomeBundle/blob/master/TerrainControl/worlds/world/WorldObjects/Structures/BranchingStructures/RuinsBasementSandstone/SandstoneRuinsBasement1.bo3#L326
is identically to Line 327

In the BirchForest*.bo3 files there spawn Birch logs from -1 to -3 underground in https://github.com/BiomeBundle/BiomeBundle/tree/master/TerrainControl/worlds/world/WorldObjects/Trees/Birch 
I think, that is not correct.

And last, the encodings of the files are sometimes Unix (LF) and sometimes Windows (CR/LF). That's only a cosmetic issue :)

But all of that is not that important. Again thank you very much for this great Terrain Control Bundle

Michael (aka BakermanLP)

**Comment by BiomeBundle** [comment]
Hey there Bakerman,

Good spot on that duplicate line I'll get that fixed and take a look at the tree too.

The encodings thing might be due to running batch files on objects as well as various other editing tools; I'll look to get the format unified in the next release. 

Thanks for your time and feedback, it really is much appreciated! Enjoy exploring your renovated terrain :)

**Comment by BakermanLP** [comment]
I can help you with some of the issues. For example I can make a pull request for the trees. I only wanted to change the kind of default trees. Some special trees like the OakForestEnchanted shouldn't be changed.

**Comment by BiomeBundle** [comment]
Tbh that birch tree was lazily fixed as it kept floating when we came across it in the world - so I just chucked on a few blocks on the end to sort it out hehe

There are a lot of trees that should have blocks less than zero; most of the spruce trees will do. Anything that's wider than one block which you've probably already realised

**Comment by BakermanLP** [comment]
I also found the following, that confuses me:

```
# The block(s) the BO3 should spawn in.
SourceBlocks: STONE:1,STONE:3,STONE:5,DIRT:1,DIRT,SAND,GRASS,DIRT:2,STATIONARY_WATER,HARD_CLAY,STAINED_CLAY,CLAY,SANDSTONE,SAND:1,AIR,STONE,GRAVEL,31,31:1,31:2,32,37,38,39,40

# The maximum percentage of the BO3 that can be outside the SourceBlock.
# The BO3 won't be placed on a location with more blocks outside the SourceBlock than this percentage.
MaxPercentageOutsideSourceBlock: 0

# What to do when a block is about to be placed outside the SourceBlock? (dontPlace, placeAnyway)
OutsideSourceBlock: placeAnyway

```
Isn't this part of a tree BO3 wrong? You make a long list of SourceBlocks that can be replaced, but then with OutsideSourceBlock you say, that everything should be placed. Or do I think wrong in this place?

**Comment by BiomeBundle** [comment]
Outsidesourceblock determines the behaviour of individual blocks. So if the tree spawns and is somehow going to intersect with a chest and destroy it, spilling it's contents, it will instead not place the single offending block. Since Maxpercentage outsidesourceblock in this case is zero it doesn't have an impact since the whole tree will cancel if more than 0% of blocks are non source blocks.

It doesn't need to be so complex for simple trees but it helps a lot when bo3s intersect, this was done en masse to many objects and as a result some of them now have complex source block settings where it's probably not needed.
