### ISSUE TITLE
[Request] Thaumcraft 6 Support

### ISSUE THREAD

**Issue by Danymaddox** [BiomeBundle/BiomeBundle#128]
Is it possible to add compatibility with the structures and the magical forest of Thaumcraft 6 (MC 1.10.2)? Thanks for your awesome work!

**Comment by ShaCraft** [comment]
I have seen both in my test worlds. It appears to already work.

**Comment by Danymaddox** [comment]
I've been testing for a while and I didn't see any Magical Forest.

**Comment by Barerock** [comment]
I've been exploring a world for a tiny bit, and both it and my survival world don't contain any structures, plants, etc. Both contain the ores though, including the crystals. I have yet to receive a loot bag from the dozens of mobs slain on my survival, and it seems that no Thaumcraft mobs exist.

**Comment by redsgreens** [comment]
I generated a Biome Bundle world and pre-generated a 4000x4000 area that has no Thaumcraft magical forests. Greatwoods are common and Silverwoods are rare but do appear, but no magical forests, which means no Pech mobs and no elevated vis levels found in the forests. You can look at the dynmap if you want to hunt for the magical forest biome yourself: http://mini.potato.systems:8123/

**Comment by BiomeBundle** [comment]
As mentioned on the wiki, OTG does not work with other mods that add biomes
to the overworld unfortunately.

**Comment by xAlicatt** [comment]
I know i'm bumping an old thread. I've seen the thaumcraft hill dungeons, ores and crystals are generating normally....but I'm getting no trees unless (oddly enough) I have dynamic trees installed with the thaumcraft compat. I've not seen magical forests yet in many worlds. Nature's compass isn't finding them. I'm pretty sure OTG adds a "magical forest" of it's own...but it's not the thaumcraft one afaik.

**Comment by xAlicatt** [comment]
That's fine. The biome doesn't matter and I understand that biomes added from other mods either won't work at all or won't work as intended. (Even though some people have claimed to see Magical forests in OTG/BB worlds) The issue is that we're not getting the trees at all, at least I'm not with the current versions of all of the mods in question. I reported this as an issue on Thaumcraft's github and Azanor claims nothing can be done on his end...which makes no sense to me since obviously Dynamic Trees is able to get the DT versions of Thaumcraft trees (and it's own vanilla replacement trees as well) to spawn in OTG/BB worlds.

**Comment by Gunner76th** [comment]
So I know this thread is now over 2 years old, however instead of opening a new ticket, I felt it best to post this here. Are there any plans to add this functionality to OTG/Biome Bundle? At present there are multiple mods that are routinely used in modpacks to which add biomes and biome specific world generation. By not supporting this aspect OTG/Biome Bundle is effectively and essentially breaking aspects of those mods. While OTG and Biome Bundle are wonderful mods for world generation, this oversight in not having compatibility and support for other mod's biome additions would be cause for some or most modpack authors to drop OTG and BiomeBundle from their packs. 

I look forward to your reply.

**Comment by BiomeBundle** [comment]
It's not possible in 1.12.2 but will be looked into when OTG updates to 1.16+
