### ISSUE TITLE
no pixelmon with pixelmon reforged and pixelmon generation

### ISSUE THREAD

**Issue by OrgeZero** [BiomeBundle/BiomeBundle#142]
no pixelmon spawn no matter the biome I'm not all done because after 50 biome different without anything
almost 9H non stop, I verfifier new world without biombundle and its present

sorry for my bad english i'm frensh

**Comment by MCPitman** [comment]
Most mob mods work automatically with Biome Bundle due to biomedict tags and inheritance of spawn lists from vanilla biomes.

If this isn't the case then you may need to manually configure pixelmon by adding the resource location IDs of the BBundle biomes to the pixelmon configs (if that's possible).
