### ISSUE TITLE
"Exception preparing structure feature" crash (Biome Bundle 4.1, MoCreatures 10.0.0.6)

### ISSUE THREAD

**Issue by Alaberti** [BiomeBundle/BiomeBundle#33]
http://pastebin.com/raw/PhgmBWXW

**Comment by MCPitman** [comment]
Looks like a problem with MoCreatures custom spawning mod though it is hard to tell since you have so many mods installed so the log may be inaccurate.

Closing this one as the report is not useful, and the modlist contains mods with known incompatibilities which are already listed here in the issues forum.
