### ISSUE TITLE
[1.10.2] Mo 'Creatures is not spawning mobs correctly

### ISSUE THREAD

**Issue by DinoGameX** [BiomeBundle/BiomeBundle#38]
I walked for 30 minutes without stopping and I found at most 2 mobs of mod Mo 'Creatures

**Comment by Neeley-Justen** [comment]
Without a crash or any more information, this issue does not help anyone.

**Comment by LiskoSlayer63** [comment]
@Neeley-Justen Actually this is a crash, very much related to #13 and #22

**Comment by Neeley-Justen** [comment]
Sorry, should have said crash log/ game log. without any more info, solving the issue is " Well, I can try to replicate, but am not sure what build you are using, what other mods are present and what interaction is causing the issue. While it is helpful to know that these are related, this issue basically just says "I have a problem, solve it."

**Comment by LiskoSlayer63** [comment]
@Neeley-Justen I think this issue is related to the fact that TerrainControl doesn't have BiomeDictionary support. So Mo' Creatures doesn't know what biome you are currently in and therefore doesn't spawn any mobs. If you put these mods to the server it will crash with a `NullPointerException` because of the same reason. I've opened this issue: [#TerrainControl/515](https://github.com/MCTCP/TerrainControl/issues/515) and I hope it'll be solved soon.

**Comment by Neeley-Justen** [comment]
You are probably right. In fact, the issue I have with pam's harvest craft is probably in the same vein. Now if I could figure out why Structuregen is breaking. Guess it's time to go back over to TC and look there.

**Comment by BiomeBundle** [comment]
A new version of Biome Bundle can be downloaded from Curse ([Forge](https://minecraft.curseforge.com/projects/biome-bundle)) or Github ([Bukkit](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0)). I expect this version to fix the issues you are experiencing (Mo Creatues & Pams), a brief changelog can be found [here](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0).

Biome Bundle is now dependant on [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) and the installation process has changed; head over to the [installation instructions](https://github.com/BiomeBundle/BiomeBundle/wiki/Installation-Instructions) that detail how to install Biome Bundle.

Please bear in mind you will need to generate a new world with the latest update as it is not compatible with old worlds. 

Happy Exploring! ☻
