### ISSUE TITLE
Sheep and other passive mob set as water creatures?

### ISSUE THREAD

**Issue by EchenCraft** [BiomeBundle/BiomeBundle#69]
Ive been going through the different biomes adding in mob spawning for various mods I have in my pack and noticed in OceanForestHighlands.bc the string for water creatures states

`SpawnWaterCreatures: [{"mob": "Sheep", "weight": 12, "min": 4, "max": 4}, {"mob": "Pig", "weight": 10, "min": 4, "max": 4}, {"mob": "Chicken", "weight": 10, "min": 4, "max": 4}, {"mob": "Cow", "weight": 8, "min": 4, "max": 4}]`

**Comment by MCPitman** [comment]
Thanks for reporting this, it is already fixed in the dev version and will be in the next release soon.

You may already know this, but Biome Bundle biomes have "InheritMobsBiomeName" set which means they will inherit mob spawn rules that mods try to apply to the vanilla biomes. Unless you want to customise it further, inheritance should handle modded mob spawning fairly well automatically.
