### ISSUE TITLE
Support for "The lost cities"

### ISSUE THREAD

**Issue by SlimF** [BiomeBundle/BiomeBundle#76]
McJty created an API for his [https://minecraft.curseforge.com/projects/the-lost-cities](url) I would like to ask if you'd be able to implement support for The lost cities. The combination with Biome Bundle would be amazing. 

Here's the thread in which McJty talked about his API [https://www.reddit.com/r/feedthebeast/comments/6hrrf3/lost_cities_support_for_other_world_types_you_can/](url)

**Comment by MCPitman** [comment]
I asked PG85 (the OTG dev) if this was a possibility and it turns out it's a lot more complicated than it first appears. Right now there are a list of development priorities that are more urgent, and with one developer doing this would only slow other things down, it's potentially something we will look at in the future though.

**Comment by LordSmellyPants** [comment]
Reopening as didn't mean to close!

**Comment by Zygus42** [comment]
If it has any relevance, this is the crash report you get when you try and teleport to a Lost Cities dimension from an OTG Biome Bundle world:
[crash-2018-02-12_13.32.59-server.txt](https://github.com/BiomeBundle/BiomeBundle/files/1715773/crash-2018-02-12_13.32.59-server.txt)

**Comment by Matrix89** [comment]
Any progress on this?

**Comment by JonJonsonsSon** [comment]
Is this possible with OTG now? If so, how?

**Comment by BiomeBundle** [comment]
Should be a feature request on the OTG tracker

**Comment by GASPOUR** [comment]
still not any progression ?
