### ISSUE TITLE
[Crash]After create map

### ISSUE THREAD

**Issue by darknat** [BiomeBundle/BiomeBundle#88]
Hi, after I have create a new map with biome bundle, my game crash instantly..

And i don't see any config file of OTG or biome bundle in my folder.

https://pastebin.com/Ke0fEZ7G

**Comment by MCPitman** [comment]
There is not really enough information here to know what the problem is and you have lots of other mods making it impossible to narrow down the cause.

I don't understand what you mean by not seeing any config file in your folder, again this is really vague so I have no idea what you are trying to say.

**Comment by JoshuaParrish** [comment]
Im having the same problem...

**Comment by MCPitman** [comment]
Without more information (crash logs) it's impossible to know what the
problem is.

**Comment by MCPitman** [comment]
No logs provided so not enough information to follow up on this.
